[config]
reload_apps = true
prefix = "@"

[templates.nvim]
input_path = "/home/baran/.config/matugen/templates/nvim-theme.lua"
output_path = "/home/baran/.config/nvim/lua/matugen_theme.lua"

[templates.cava]
input_path = "/home/baran/.config/matugen/templates/cava.template"
output_path = "/home/baran/.config/cava/themes/matugen"
